---

hostname_fqdn: "{{ inventory_hostname }}"
localtime_zone:
  FreeBSD: Asia/Phnom_Penh
  Debian: Asia/Phnom_Penh
project_backend_url: "wss://{{ project_backend_address }}:8081"

# __________________________________________agent
os_project_naigos_plugin_dir:
  FreeBSD: /usr/local/libexec/nagios
  OpenBSD: /usr/local/libexec/nagios
  Debian: /usr/lib/nagios/plugins
  RedHat: FIXME

os_project_sensu_plugin_dir:
  FreeBSD: "{{ sensu_go_agent_home }}/.gem/ruby/{{ language_ruby_version['major'] }}.{{ language_ruby_version['minor'] }}/bin"
  Debian: "{{ sensu_go_agent_home }}/.gem/ruby/{{ language_ruby_version['major'] }}.{{ language_ruby_version['minor'] }}/bin"

project_agent_label:
  nagios_plugin_dir: "{{ os_project_naigos_plugin_dir[ansible_os_family] }}"
  sensu_plugin_dir: "{{ os_project_sensu_plugin_dir[ansible_os_family] }}"

os_sensu_go_agent_flags:
  FreeBSD: ""
  Debian: ""
  RedHat: ""
sensu_go_agent_flags: "{{ os_sensu_go_agent_flags[ansible_os_family] }}"

sensu_go_agent_ruby_plugins:
  - sensu-plugin
  - sensu-plugins-disk-checks

project_sensu_go_agent_keepalive_warning_timeout: 120
project_sensu_go_agent_keepalive_critical_timeout: 300
# __________________________________________packege
freebsd_pkg_repo:

  # disable the default package repository
  FreeBSD:
    enabled: "false"
    state: present

  # enable my own package repository, where the latest package is
  # available
  FreeBSD_devel:
    enabled: "true"
    state: present
    url: "http://pkg.i.trombik.org/{{ ansible_distribution_version | regex_replace('\\.', '') }}{{ansible_architecture}}-default-default/"
    mirror_type: http
    signature_type: none
    priority: 100

# see https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh
apt_repo_keys_to_add:
  - https://packagecloud.io/sensu/stable/gpgkey
apt_repo_to_add:
  - deb https://packagecloud.io/sensu/stable/ubuntu/ {{ ansible_distribution_release }} main
apt_repo_enable_apt_transport_https: True

redhat_repo_extra_packages:
  - epel-release

# see https://packagecloud.io/install/repositories/sensu/stable/config_file.repo?os=centos&dist=7&source=script
redhat_repo:
  sensu:
    baseurl: "https://packagecloud.io/sensu/stable/el/{{ ansible_distribution_major_version }}/$basearch"

    # Package sensu-go-cli-5.19.1-10989.x86_64.rpm is not signed
    gpgcheck: no
    enabled: yes
  epel:
    mirrorlist: "http://mirrors.fedoraproject.org/mirrorlist?repo=epel-{{ ansible_distribution_major_version }}&arch={{ ansible_architecture }}"
    gpgcheck: yes
    enabled: yes
