---

hostname_fqdn: "{{ inventory_hostname }}"
localtime_zone:
  FreeBSD: Asia/Phnom_Penh
  Debian: Asia/Phnom_Penh

resolver_config: |
  nameserver 192.168.99.251
  domain {{ ansible_domain }}
  FreeBSD: Asia/Bangkok

# __________________________________________agent
os_project_agent_label:
  FreeBSD:
    nagios_plugin_dir: /usr/local/libexec/nagios
  OpenBSD:
    nagios_plugin_dir: /usr/local/libexec/nagios
  Debian:
    nagios_plugin_dir: /usr/lib64/nagios/plugins
  RedHat:
    nagios_plugin_dir: /usr/lib64/nagios/plugins
project_agent_label: "{{ os_project_agent_label[ansible_os_family] }}"

sensu_go_agent_config:
  backend-url: ws://172.16.100.254:8081
  cache-dir: "{{ sensu_go_agent_cache_dir }}"
  subscriptions:
    - system
  labels: "{{ project_agent_label }}"

os_sensu_go_agent_flags:
  FreeBSD: ""
  Debian: ""
  RedHat: ""
sensu_go_agent_flags: "{{ os_sensu_go_agent_flags[ansible_os_family] }}"

# __________________________________________packege
freebsd_pkg_repo:

  # disable the default package repository
  FreeBSD:
    enabled: "false"
    state: present

  # enable my own package repository, where the latest package is
  # available
  FreeBSD_devel:
    enabled: "true"
    state: present
    url: "http://pkg.i.trombik.org/{{ ansible_distribution_version | regex_replace('\\.', '') }}{{ansible_architecture}}-default-default/"
    mirror_type: http
    signature_type: none
    priority: 100

# see https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh
apt_repo_keys_to_add:
  - https://packagecloud.io/sensu/stable/gpgkey
apt_repo_to_add:
  - deb https://packagecloud.io/sensu/stable/ubuntu/ bionic main
apt_repo_enable_apt_transport_https: True

redhat_repo_extra_packages:
  - epel-release

# see https://packagecloud.io/install/repositories/sensu/stable/config_file.repo?os=centos&dist=7&source=script
redhat_repo:
  sensu:
    baseurl: "https://packagecloud.io/sensu/stable/el/{{ ansible_distribution_major_version }}/$basearch"

    # Package sensu-go-cli-5.19.1-10989.x86_64.rpm is not signed
    gpgcheck: no
    enabled: yes
  epel:
    mirrorlist: "http://mirrors.fedoraproject.org/mirrorlist?repo=epel-{{ ansible_distribution_major_version }}&arch={{ ansible_architecture }}"
    gpgcheck: yes
    enabled: yes
