---

# __________________________________________backend
os_sensu_go_backend_extra_packages:
  FreeBSD: sysutils/sensu-go-cli
  Debian: sensu-go-cli
  RedHat: sensu-go-cli
sensu_go_backend_extra_packages: "{{ os_sensu_go_backend_extra_packages[ansible_os_family] }}"
sensu_go_backend_admin_account: admin
sensu_go_backend_admin_password: P@ssw0rd!
sensu_go_backend_config:
  state-dir: "{{ sensu_go_backend_state_dir }}"
  cache-dir: "{{ sensu_go_backend_cache_dir }}"
  log-level: debug
  agent-host: "[::]"
  api-listen-address: "[::]:8080"
  dashboard-host: "[::]"
  dashboard-port: 3000

os_sensu_go_backend_flags:
  FreeBSD: ""
  Debian: ""
  RedHat: ""
sensu_go_backend_flags: "{{ os_sensu_go_backend_flags[ansible_os_family] }}"
