---
project_backend_address: sensu1.i.trombik.org
project_sudo_configs_local:
  - name: 100_root
    content: |
      root ALL=(ALL) NOPASSWD: ALL
  - name: root
    state: absent
    content: ""
  - name: vagrant
    state: absent
    content: ""
hosts_extra_localhosts: []
