---
project_sensu_go_backend_config_log_level: info
project_backend_listen_url: "https://{{ ansible_host }}"
project_backend_etcd_listen_url: "https://{{ project_backend_address }}"
project_cfssl_certs:
  - name: sensu1.i.trombik.org.json
    SAN:
      - 127.0.0.1
      - localhost
      - sensu1
      # XXX because etcd does not use DNS name, you need to list IP addresses
      # here
      - "{{ ansible_default_ipv4['address'] }}"
      # XXX golang does not check CN if SAN exists. you need FQDN in SAN
      #
      # RFC6125 says:
      # As noted, a client MUST NOT seek a match for a reference identifier
      # of CN-ID if the presented identifiers include a DNS-ID, SRV-ID,
      # URI-ID, or any application-specific identifier types supported by the
      # client.
      # https://tools.ietf.org/html/rfc6125#section-6.4.4
      - "{{ ansible_host }}"
    profile: backend
    owner: sensu
    json:
      CN: sensu1.i.trombik.org
      hosts:
        - ""
      key:
        algo: rsa
        size: 2048
  - name: mqtt.i.trombik.org.json
    profile: backend
    owner: root
    SAN:
      - mqtt.i.trombik.org
    json:
      CN: mqtt.i.trombik.org
      names:
        - C: KH
          O: MKRS Siem Reap
      key:
        algo: rsa
        size: 2048
