---

os_sensu_go_agent_extra_packages:
  FreeBSD:
    - sysutils/sensu-go-cli
    - net-mgmt/nagios-plugins
  Debian: []
  RedHat:
  OpenBSD: []
sensu_go_agent_extra_packages: "{{ os_sensu_go_agent_extra_packages[ansible_os_family] }}"

sensu_go_agent_config:
  backend-url: "{{ project_backend_url }}"
  cache-dir: "{{ sensu_go_agent_cache_dir }}"
  subscriptions:
    - system
  labels: "{{ project_agent_label }}"
  keepalive-warning-timeout: "{{ project_sensu_go_agent_keepalive_warning_timeout }}"
  keepalive-critical-timeout: "{{ project_sensu_go_agent_keepalive_critical_timeout }}"
