---
sensu_go_backend_admin_account: admin
sensu_go_backend_admin_password: P@ssw0rd!
project_readonly_user: readonly
project_readonly_pass: PassWord

# XXX slack remove webhook urls found in public repositories. use b64encoded
# string to fool slack.
#
# to encode, use:
#
# echo -n 'https://url/to/webhook' | b64encode -r - | tr -d '\n'; echo
project_slack_webhook_url: "{{ 'aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAxM0xSTkJRMzAvQjAxNFFNMDcwU0MvSXBGWTNReWxLMkJjaVNEU0dtZ1pINWhk' | b64decode }}"
