---
project_backend_address: 172.16.100.254
project_sudo_configs_local:
  - name: 100_root
    content: |
      root ALL=(ALL) NOPASSWD: ALL
  - name: 999_vagrant
    content: |
      Defaults:vagrant !requiretty
      vagrant ALL=(ALL) NOPASSWD: ALL
  - name: root
    state: absent
    content: ""
  - name: vagrant
    state: absent
    content: ""
hosts_extra_localhosts:
  - "{{ inventory_hostname }}"
  - "{{ inventory_hostname.split('.') | first }}"
