---
language: ruby
rvm:
  - 2.6
cache: bundler

# Use the new container infrastructure
sudo: false
bundler_args: --binstubs --with development

before_install:

  # Use bundler 2.x
  - gem install bundler

install:
  - npm install
  - pip3 install yamllint

scripts:
  - rake test:rubocop:all
  - node node_modules/markdownlint-cli/markdownlint.js .
  - yamllint -c .yamllint.yml
