---
language: ruby
rvm:
  - 2.6
cache: bundler
bundler_args: --binstubs --with development

before_install:
  - npm install
  - pip install yamllint

  # Use bundler 2.x
  - gem install bundler

scripts:
  - rake test:rubocop:all
  - node node_modules/markdownlint-cli/markdownlint.js .
  - yamllint -c .yamllint.yml
