---
language: ruby
rvm:
  - 2.6
cache: bundler

# Use the new container infrastructure
sudo: false

before_install:

  # Use bundler 2.x
  - gem install bundler

install:
  - npm install

  # XXX without this, pip3 fails with
  # `The `pip3' command exists in these Python versions:`
  - pyenv global 3.7
  - pip3 install --user yamllint
  - bundle install --path=vendor/bundle --with development

scripts:
  - bundle exec rake test:rubocop:all
  - node node_modules/markdownlint-cli/markdownlint.js .
  - yamllint -c .yamllint.yml .
