---
extends: default

rules:
  line-length: disable

  # ansible accepts many forms of trueness
  truthy: disable

ignore: |
  # yamllint does not understand erb template
  vendor
  node_modules
  roles.galaxy
  collections.galaxy
  playbooks/group_vars/prod.yml
  ruby
