---
all:
  hosts:
    sensu1.i.trombik.org:
      ansible_host: sensu1.i.trombik.org
  children:
    backend:
      hosts:
        sensu1.i.trombik.org:
    prod-backend:
      children:
        backend:
    prod-credentials:
      children:
        backend:
    prod:
      children:
        backend:
