---
all:
  hosts:
    sensu1.i.trombik.org:
      ansible_host: sensu1.i.trombik.org
  children:
    backend:
      hosts:
        sensu1.i.trombik.org:
    target:
      hosts:
        sensu1.i.trombik.org:
    virtualbox-backend:
      children:
        backend:
    virtualbox-target:
      children:
        target:
    virtualbox-credentials:
      children:
        backend:
        target:
    virtualbox:
      children:
        backend:
        target:
