---

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create trombik user
  user:
    comment: Tomoyuki Sakurai
    create_home: yes
    group: "{{ users_default_group }}"
    groups: "{{ users_default_groups }}"
    name: trombik
    password: "{{ project_trombik_password }}"
    shell: "{{ users_default_shell }}"

- name: Create trombik's ssh key
  authorized_key:
    key: https://github.com/trombik.keys
    comment: y@trombik.org
    user: trombik
