---
- hosts:
    - virtualbox-target
  become: yes
  become_user: root
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"
  roles:
    - name: trombik.hostname
    - name: trombik.localtime
    - name: trombik.hosts
    - name: trombik.freebsd_pkg_repo
      when: ansible_os_family == 'FreeBSD'
    - name: trombik.apt_repo
      when: ansible_os_family == 'Debian'
    - name: trombik.sudo
    - name: trombik.vim
    - name: trombik.zsh
    - name: trombik.git
    - name: trombik.language_ruby
    - name: users
    - name: trombik.nginx
    - name: trombik.sensu_go_agent
    - name: trombik.monit
